# service config 'qa'
spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://localhost:3306/ms_account?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy

eureka:
  instance:
    hostName: qa.eureka.bcbs.org
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    fetch-registry: false
