# service config 'production'
spring:
  profiles: production

eureka:
  environment: Production
  instance:
    hostName: prod.eureka.bcbs.org
  server:
    eviction-interval-timer-in-ms: 600000
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: ERROR
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
