# service config 'production'
spring:
  profiles: production

eureka:
  environment: Production
  instance:
    hostName: prod.eureka.bcbs.org
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostName}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: ERROR
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
