# service config 'production'
spring:
  profiles: production

eureka:
  instance:
    hostName: prod.eureka.bcbs.org
    metadata-map:
      cluster: ApiGateway
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/

api-gateway:
  transmission:
    cache: true
    crypto: true

zuul:
  ignored-services: "*"
  routes:
    Evaluation-Service:
      path: /eval/**
    Examination-Service:
      path: /exam/**
    Organization-Service:
      path: /org/**
    Training-Service:
      path: /train/**
