# service config 'qa'
spring:
  profiles: qa

eureka:
  instance:
    hostName: qa.eureka.bcbs.org
    metadata-map:
      cluster: ApiGateway
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    registry-fetch-interval-seconds: 60

api-gateway:
  data-crypto: true

zuul:
  ignored-services: "*"
  routes:
    Evaluation-Service:
      path: /eval/**
    Examination-Service:
      path: /exam/**
    Organization-Service:
      path: /org/**
    Training-Service:
      path: /train/**
