# service config 'qa'
spring:
  profiles: qa

eureka:
  instance:
    hostName: qa.eureka.bcbs.org
    leaseRenewalIntervalInSeconds: 60
    metadata-map:
      cluster: ApiGateway
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostName}:8761/eureka/

api-gateway:
  transmission:
    cache: true
    crypto: true

zuul:
  ignored-services: "*"
  routes:
    Evaluation-Service:
      path: /eval/**
    Examination-Service:
      path: /exam/**
    Organization-Service:
      path: /org/**
    Training-Service:
      path: /train/**
