server:
  port: 8761

---
# service config 'development'
spring:
  profiles: development

eureka:
  environment: Development
  instance:
    hostName: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO
    com:
      netflix:
        eureka: INFO
        discovery: INFO
