server:
  port: 13002

---
# service config 'development'
spring:
  profiles: development

eureka:
  instance:
    hostName: localhost
    lease-expiration-duration-in-seconds: 180
    lease-renewal-interval-in-seconds: 60
    metadata-map:
      cluster: ApiGateway
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    registry-fetch-interval-seconds: 5

api-gateway:
  data-crypto: false

zuul:
  ignored-services: "*"
  ribbon-isolation-strategy: thread
  routes:
    Evaluation-Service:
      path: /eval/**
    Examination-Service:
      path: /exam/**
    Organization-Service:
      path: /org/**
    Training-Service:
      path: /train/**
