server:
  port: 13002

---
# service config 'development'
spring:
  profiles: development

eureka:
  instance:
    hostName: localhost
    leaseRenewalIntervalInSeconds: 60
    metadata-map:
      cluster: ApiGateway
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostName}:8761/eureka/

api-gateway:
  transmission:
    cache: false
    crypto: false

zuul:
  ignored-services: "*"
  ribbon-isolation-strategy: thread
  routes:
    Evaluation-Service:
      path: /eval/**
    Examination-Service:
      path: /exam/**
    Organization-Service:
      path: /org/**
    Training-Service:
      path: /train/**
