server:
  port: 8989

---
# service config 'development'
spring:
  profiles: development

eureka:
  instance:
    hostName: localhost
    lease-expiration-duration-in-seconds: 180
    lease-renewal-interval-in-seconds: 60
  client:
    service-url:
      default-zone: http://${eureka.instance.hostName}:8761/eureka/
    prefer-same-zone-eureka: false
    register-with-eureka: false

turbine:
  aggregator:
    clusterConfig: ApiGateway
  appConfig: Mobile-Gateway, Web-Gateway
  clusterNameExpression: metadata['cluster']
